services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}  # This passes the .env variable as build arg
        - VITE_BASE_URL=${VITE_BASE_URL}  # This passes the .env variable as build arg
    container_name: wallet-app-frontend
    ports:
      - "3001:80"
